### PR TITLE
[Feature] JSON body `i()` now works with strings. Added better error messages also.

### PR DESCRIPTION
**Pull request by SamuelMarks**

### CODE REVIEW

**Comment by SamuelMarks** [comment]
Issue: when something other than a string or number is passed through, the server crashes.

PS: I've confirmed that `get_type_str(t())` is returning the correct thing.

**Comment by ipkn** [comment]
Thank you. I tested i() works well with string.

**Comment by SamuelMarks** [comment]
@ipkn: Great, thanks for merging. BTW: any ideas about that crash, or does it work for you?

**Comment by ipkn** [comment]
Does it crash? I think it is terminated by an  uncaughted exception. If we need more safe method, we need to add another interface to get the value.

**Comment by SamuelMarks** [comment]
@ipkn Yeah, pass through something that is neither a string nor a number, and you'll see what I mean.

`get_type_str(t())` isn't causing the crash, which is weird as that's all in `default`.

**Pull request merged**
